Config = Config or {}

Config.MinZOffset = 30

Config.RamsNeeded = 2

Config.Houses = {}

Config.Furniture = {
	["sofas"] = {
		label = "Sofas",
		items = {
			[1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["label"] = "sofá viejo" },
			[2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["label"] = "Sofá viejo" },
			[3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["label"] = "silla vieja" },
			[4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["label"] = "sofá viejo" },
			[5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["label"] = "viejo sofá rayado" },
			[6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["label"] = "Viejo sofá de asiento amarillo" },
			[7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["label"] = "Sofá de esquina" },
			[8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["label"] = "Sofá de esquina 2 " },
			[9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["label"] = "Sofá 1 " },
			[10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["label"] = "Sofá 2" },
			[11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["label"] = "Sofá 3" },
			[12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["label"] = "Sofá 4 " },
			[13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["label"] = "Sofá 5" },
			[14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["label"] = "Sofá 6" },
			[15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["label"] = "Sofá 7" },
			[16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["label"] = "Sofá 8" },
			[17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["label"] = "Sofá9" },
			[18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["label"] = "Sofá 10" },
			[19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["label"] = "Sofá 11" },
			[20] = { ["object"] = "v_ilev_m_sofa", ["price"] = 2000, ["label"] = "Sofá blanco" },
			[21] = { ["object"] = "v_med_p_sofa", ["price"] = 1000, ["label"] = "Sofá de cuero marrón" },
			[22] = { ["object"] = "v_club_officesofa", ["price"] = 500, ["label"] = "Sofá rojo" },
			[23] = { ["object"] = "bkr_prop_clubhouse_sofa_01a", ["price"] = 1000, ["label"] = "Sofá negro" },
			[24] = { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 5000, ["label"] = "Sofá de esquina 3" },
			[25] = { ["object"] = "prop_couch_lg_02", ["price"] = 1000, ["label"] = "Maderas de sofá" },
			[26] = { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 5000, ["label"] = "Sofá de esquina 4" },
			[27] = { ["object"] = "apa_mp_h_yacht_sofa_02", ["price"] = 1000, ["label"] = "Sofá marrón" },
			[28] = { ["object"] = "apa_mp_h_yacht_sofa_01", ["price"] = 5000, ["label"] = "Sofá largo blanco" }
		},
	},
	["chairs"] = {
		label = "Sillas",
		items = {
			[1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["label"] = "Silla alta" },
			[2] = { ["object"] = "apa_mp_h_stn_chairstrip_03", ["price"] = 500, ["label"] = "Silla 4" },
			[3] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["label"] = "Silla" },
			[4] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["label"] = "Silla 2" },
			[5] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["label"] = "Silla alta 2" },
			[6] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["label"] = "Silla de cocina 1 " },
			[7] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["label"] = "Silla de cocina 2" },
			[8] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["label"] = "Silla de cocina 3" },
			[9] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["label"] = "Silla 3" },
			[10] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["label"] = "Silla 4" },
			[11] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["label"] = "Silla alta 3" },
			[12] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["label"] = "Sillón" },
			[13] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["label"] = "Silla de cocina 4" },
			[14] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["label"] = "Silla 5" },
			[15] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["label"] = "Silla de MB" },
			[16] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["label"] = "Silla de brazo 2" },
			[17] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["label"] = "Silla de cocina 5" },
			[18] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["label"] = "Silla de estudio" },
			[19] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["label"] = "Marco de silla" },
			[20] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["label"] = "Silla 5" },
			[21] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["label"] = "Silla de oficina" },
			[22] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["label"] = "Silla 6" },
			[23] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["label"] = "Silla de cuero" },
			[24] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["label"] = "Silla scuz" },
			[25] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["label"] = "Silla de escritorio" },
			[26] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["label"] = "Silla fácil" },
			[27] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["label"] = "Silla de mimbre" },
			[28] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["label"] = "Silla de directores" },
			[29] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["label"] = "Silla de directores 2" },
			[30] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["label"] = "Silla de yate 1" },
			[31] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["label"] = "Silla de yate 2" },
			[32] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["label"] = "Silla de yate 3" },
			[33] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["label"] = "Silla de yate 4" },
			[34] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["label"] = "Silla blanca" },
			[35] = { ["object"] = "v_ret_chair", ["price"] = 100, ["label"] = "Silla 7" },
			[36] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["label"] = "Sillón" },
			[37] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["label"] = "Silla de oficina 2" },
			[38] = { ["object"] = "apa_mp_h_yacht_armchair_01", ["price"] = 1000, ["label"] = "Butaca blanca" },
			[39] = { ["object"] = "v_club_barchair", ["price"] = 300, ["label"] = "Silla 8" },
			[40] = { ["object"] = "prop_off_chair_04", ["price"] = 300, ["label"] = "Silla de escritorio 2" },
			[41] = { ["object"] = "v_club_stagechair", ["price"] = 500, ["label"] = "Sillón rosa" },
			[42] = { ["object"] = "v_club_officechair", ["price"] = 500, ["label"] = "Silla de escritorio 3" },
			[43] = { ["object"] = "prop_armchair_01", ["price"] = 500, ["label"] = "Silla" },
			[44] = { ["object"] = "prop_bar_stool_01", ["price"] = 300, ["label"] = "Taburete de bar" },
			[45] = { ["object"] = "apa_mp_h_yacht_stool_01", ["price"] = 300, ["label"] = "Puffe blanco" },
			[46] = { ["object"] = "apa_mp_h_stn_chairarm_12", ["price"] = 500, ["label"] = "Silla 3" },
			[47] = { ["object"] = "apa_mp_h_stn_chairstool_12", ["price"] = 300, ["label"] = "Descanso de pies" },
			[48] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["label"] = "Sillón GC 01" },
			[49] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["label"] = "Sillón GC 02" },
			[50] = { ["object"] = "prop_chair_03", ["price"] = 100, ["label"] = "Silla de madera" }
		},
	},
	["beds"] = {
		label = "Camas",
		items = {
			[1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["label"] = "Cama naranja" },	
			[2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["label"] = "Cama de madera pequeña" },	
			[3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["label"] = "Cama clásica marrón" },	
			[4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["label"] = "Boda clásica blanca " },	
			[5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["label"] = "Cama de cuero" },	
			[6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["label"] = "Cama de madera verde" },	
			[7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["label"] = "Cama de madera azul" },	
			[8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["label"] = "Cama" },
			[9] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 5000, ["label"] = "Cama moderna" },
			[10] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 5000, ["label"] = "Cama roja" },
			[11] = { ["object"] = "bkr_prop_biker_campbed_01", ["price"] = 100, ["label"] = "Cama de camping" },
			[12] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["label"] = "Almohada 1" },
			[13] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["label"] = "Almohada 2" },
			[14] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["label"] = "Almohada 3" },
			[15] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["label"] = "Almohada 4" },
			[16] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["label"] = "Almohada 5" },
			[17] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["label"] = "Almohada 6" },
			[18] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["label"] = "Almohada 7" }
		},	
	},
	["general"] = {
		label = "General",
		items = {
			[1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["label"] = "Bolsa de frijoles1" },
			[2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["label"] = "Jarrón blanco" },
			[3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["label"] = "Pared acolchada" },
			[4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["label"] = "Ram Skull." },
			[5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["label"] = "Látigos" },
			[6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["label"] = "Revista" },
			[7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["label"] = "Revista abierta" },
			[8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["label"] = "Revista 2" },
			[9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["label"] = "Alfombra de yoda 1" },
			[10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["label"] = "Alfombra de yoda 2" },
			[11] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["label"] = "Alfombra de yoda 3" },
			[12] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["label"] = "Alfombra de yoda 4" },
			[13] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["label"] = "Alfombra de yoda 5" },
			[14] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["label"] = "Aftershave" },
			[15] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["label"] = "Canasta de frutas" },
			[16] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["label"] = "Cesto de la ropa" },
			[17] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["label"] = "Puff" },
			[18] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["label"] = "Estatua grande" },
			[19] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["label"] = "Revista 3" },
			[20] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["label"] = "Joyero" },
			[21] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["label"] = "Papelera" },
			[22] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["label"] = "Canasta de frutas" },
			[23] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["label"] = "Jarrón de bronce" },
			[24] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["label"] = "Tablero de tiza" },
			[25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["label"] = "Cenicero azul" },
			[26] = { ["object"] = "prop_ashtray_01", ["price"] = 100, ["label"] = "Cenicero negro" },
			[27] = { ["object"] = "v_ret_fh_ashtray", ["price"] = 100, ["label"] = "Cenicero piedra" },
			[28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["label"] = "Escala" },
			[29] = { ["object"] = "v_med_cor_whiteboard", ["price"] = 300, ["label"] = "pizarron" },
			[30] = { ["object"] = "apa_mp_h_acc_rugwooll_04", ["price"] = 500, ["label"] = "Alfombra 1" },
			[31] = { ["object"] = "ex_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "Alfombra 2" },
			[32] = { ["object"] = "apa_mp_h_acc_rugwoolm_03", ["price"] = 500, ["label"] = "Alfombra 3" },
			[33] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 500, ["label"] = "Alfombra 4" },
			[34] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "Alfombra 5" },
			[35] = { ["object"] = "hei_mpheist_yacht_ab_03", ["price"] = 500, ["label"] = "Piano" }
		},
	},
	["general2"] = {
		label = "Objetos",
		items = {
			[1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["label"] = "Pila de papeles 1" },
			[2] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["label"] = "Pila de papeles 2" },
			[3] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["label"] = "Archivador" },
			[4] = { ["object"] = "v_med_p_notebook", ["price"] = 100, ["label"] = "Notas" },
			[5] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["label"] = "Caja con papeles" },
			[6] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["label"] = "Botella de alcohol" },
			[7] = { ["object"] = "ba_prop_club_champset", ["price"] = 300, ["label"] = "Conjunto de champagne" },
			[8] = { ["object"] = "prop_champ_cool", ["price"] = 100, ["label"] = "Enfriador de champagne" },
			[9] = { ["object"] = "prop_champ_01b", ["price"] = 100, ["label"] = "Botella de champagne" },
			[10] = { ["object"] = "prop_champ_flute", ["price"] = 100, ["label"] = "Copa de champán 1" },
			[11] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["label"] = "Copa de champán 2" },
			[12] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["label"] = "Botella de whisky" },
			[13] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["label"] = "Vaso de whisky" },
			[14] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["label"] = "Botella de cerveza" },
			[15] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["label"] = "Caja de cerveza 1" },
			[16] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["label"] = "Caja de cerveza 2" },
			[17] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["label"] = "Prismáticos" },
			[18] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["label"] = "Spray Blox" },
			[19] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["label"] = "Bongos" },
			[20] = { ["object"] = "prop_bong_01", ["price"] = 100, ["label"] = "Bong" },
			[21] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["label"] = "Boombox" },
			[22] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["label"] = "Cuenco de crips" },
			[23] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["label"] = "Dulce" },
			[24] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["label"] = "Bolsa 247" },
			[25] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["label"] = "Bolsa de papel" },
			[26] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["label"] = "Saco" },
			[27] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["label"] = "Contenedor de basura" },
			[28] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["label"] = "Jarra de cerámica" },
			[29] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["label"] = "Paquete de cigarrillos 1" },
			[30] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["label"] = "Paquete de cigarrillos 2" },
			[31] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["label"] = "taza" },
			[32] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["label"] = "Sobre" },
			[33] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["label"] = "Mochila" },
			[34] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["label"] = "DVD" },
			[35] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["label"] = "Caja de DVD" },
			[36] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["label"] = "Caja de película" },
			[37] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["label"] = "Tabla de planchar" },
			[38] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["label"] = "Katana" },
			[39] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["label"] = "Caja diesel" },
			[40] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["label"] = "Botella de medicamentos 1" },
			[41] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["label"] = "Botella de medicamentos 2" },
			[42] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["label"] = "Bong" },
			[43] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["label"] = "{Cacahuetes}" },
			[44] = { ["object"] = "p_cs_lighter_01", ["price"] = 100, ["label"] = "Mechero" },
			[45] = { ["object"] = "p_cs_papers_01", ["price"] = 100, ["label"] = "Papel de fumar" },
			[46] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["label"] = "Vela" },
			[47] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["label"] = "Vela grande" },
			[48] = { ["object"] = "v_res_fa_candle01", ["price"] = 100, ["label"] = "Vela azul" },
			[49] = { ["object"] = "v_res_fa_candle02", ["price"] = 100, ["label"] = "Vela roja" },
			[50] = { ["object"] = "v_res_fa_candle03", ["price"] = 100, ["label"] = "Vela verde" },
			[51] = { ["object"] = "v_res_fa_candle04", ["price"] = 100, ["label"] = "Vela pequeña" },
			[52] = { ["object"] = "v_med_bottles2", ["price"] = 100, ["label"] = "químicos" },
			[53] = { ["object"] = "v_res_desktidy", ["price"] = 100, ["label"] = "Material de oficina" },
			[54] = { ["object"] = "bkr_prop_weed_dry_01a", ["price"] = 100, ["label"] = "Pila de maleza" },
			[55] = { ["object"] = "ba_prop_battle_trophy_battler", ["price"] = 100, ["label"] = "Trofeo de puño" },
			[56] = { ["object"] = "ba_prop_battle_trophy_no1", ["price"] = 100, ["label"] = "Trofeo estrella" },
			[57] = { ["object"] = "prop_golf_bag_01c", ["price"] = 100, ["label"] = "bolsa de golf" },
			[58] = { ["object"] = "hei_heist_kit_bin_01", ["price"] = 100, ["label"] = "Papelera" },
			[59] = { ["object"] = "prop_wooden_barrel", ["price"] = 100, ["label"] = "Barril de madera" },
			[60] = { ["object"] = "prop_mb_sandblock_01", ["price"] = 100, ["label"] = "Bloque de arena x1" },
			[61] = { ["object"] = "prop_mb_sandblock_02", ["price"] = 100, ["label"] = "Bloque de arena x3" },
			[62] = { ["object"] = "p_pallet_02a_s", ["price"] = 100, ["label"] = "Palet" },
			[63] = { ["object"] = "ch_chint03_pallet_pile_01", ["price"] = 100, ["label"] = "Palet apilado" },
			[64] = { ["object"] = "ex_prop_crate_money_bc", ["price"] = 100, ["label"] = "Palet con dinero" },
			[65] = { ["object"] = "hei_prop_heist_weed_pallet", ["price"] = 100, ["label"] = "Palet con hierba" },
			[66] = { ["object"] = "sm_prop_smug_crate_m_narc", ["price"] = 100, ["label"] = "Palet con hierba 2" },	
			[67] = { ["object"] = "prop_paints_pallete01", ["price"] = 100, ["label"] = "Palet con pintura" },
			[68] = { ["object"] = "ex_prop_crate_art_02_sc", ["price"] = 100, ["label"] = "Palet con obra de arte" },
			[69] = { ["object"] = "sm_prop_smug_crate_m_medical", ["price"] = 100, ["label"] = "Palet con materia médica" },
			[70] = { ["object"] = "sm_prop_smug_crate_m_tobacco", ["price"] = 100, ["label"] = "Palet con tabaco" },
			[71] = { ["object"] = "sm_prop_smug_crate_s_jewellery", ["price"] = 100, ["label"] = "Palet con joyas" },
			[72] = { ["object"] = "p_secret_weapon_02", ["price"] = 100, ["label"] = "Palet con milcrates" },
			[73] = { ["object"] = "bkr_prop_bkr_cashpile_01", ["price"] = 100, ["label"] = "Pila de dinero 1" },
			[74] = { ["object"] = "bkr_prop_bkr_cashpile_05", ["price"] = 100, ["label"] = "Pila de dinero 2" },
			[75] = { ["object"] = "prop_flattruck_01d", ["price"] = 100, ["label"] = "Trolly con cajas" },
			[76] = { ["object"] = "bkr_int_w03_pallettruck", ["price"] = 100, ["label"] = "Palet de transporte" },
			[77] = { ["object"] = "v_55_tor_mesh_forklift", ["price"] = 100, ["label"] = "Máquina elevadora" },
			[78] = { ["object"] = "prop_rub_pile_03", ["price"] = 100, ["label"] = "Llantas" },
			[79] = { ["object"] = "sm_prop_smug_crate_s_jewellery", ["price"] = 100, ["label"] = "Joyas de caja negra" },
			[80] = { ["object"] = "ex_office_swag_guns02", ["price"] = 100, ["label"] = "Cajas de munición" },
			[81] = { ["object"] = "v_ilev_fib_door3", ["price"] = 100, ["label"] = "Puerta" }
		},
	},
	["general3"] = {
		label = "Random",
		items = {
			[1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["label"] = "Papelera 1" },
			[2] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["label"] = "Papelera 2" },
			[3] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["label"] = "Cesto de la ropa" },
			[4] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["label"] = "Bolsa de lona 1" },
			[5] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["label"] = "Bolsa de lona 2" },
			[6] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["label"] = "Bolsa de lona 3" },
			[7] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["label"] = "Recepción de efectivo" },
			[8] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["label"] = "Reloj" },
			[9] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["label"] = "Bolso de cuero 1" },
			[10] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["label"] = "Bolso de cuero 2" },
			[11] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["label"] = "Bolso de cuero abierto" },
			[12] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["label"] = "Libro 1" },
			[13] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["label"] = "Libro 2" },
			[14] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["label"] = "Libro 3" },
			[15] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["label"] = "Libro 4" },
			[16] = { ["object"] = "v_res_fa_book03", ["price"] = 100, ["label"] = "Libro 5" },
			[17] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["label"] = "Cámara" },
			[18] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["label"] = "Héroe de la estatua" },
			[19] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["label"] = "Revista 1" },
			[20] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["label"] = "Revista 2" },
			[21] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["label"] = "Rosa cráneo" },
			[22] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["label"] = "Guitarra 1" },
			[23] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["label"] = "Guitarra 2" },
			[24] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["label"] = "Guitarra 3" },
			[25] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["label"] = "Guitarra 3" },
			[26] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["label"] = "Maletin" },
			[27] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["label"] = "Bolsa de la compra" },
			[28] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["label"] = "Botella" },
			[29] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["label"] = "Voodoo" }, 
			[30] = { ["object"] = "prop_weight_rack_02", ["price"] = 500, ["label"] = "Mancuerna" },
			[31] = { ["object"] = "prop_weight_bench_02", ["price"] = 500, ["label"] = "Prensa de bancot" },
			[32] = { ["object"] = "prop_tool_broom", ["price"] = 100, ["label"] = "Palo de escoba" },
			[33] = { ["object"] = "prop_fire_exting_2a", ["price"] = 100, ["label"] = "Extintor de incendios" },
			[34] = { ["object"] = "v_res_vacuum", ["price"] = 100, ["label"] = "Aspiradora" },
			[35] = { ["object"] = "v_ret_gc_fan", ["price"] = 100, ["label"] = "Ventilador" },
			[36] = { ["object"] = "prop_paint_stepl01b", ["price"] = 100, ["label"] = "Escalera" },
			[37] = { ["object"] = "bkr_prop_weed_bucket_01b", ["price"] = 100, ["label"] = "Fertilizante 1" },
			[38] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["label"] = "Fertilizante 2" },
			[39] = { ["object"] = "v_club_vusnaketank", ["price"] = 500, ["label"] = "Terrario " },
			[40] = { ["object"] = "prop_pooltable_02", ["price"] = 1500, ["label"] = "Mesa de billar" },
			[41] = { ["object"] = "prop_pool_rack_02", ["price"] = 100, ["label"] = "Poolcues" },
			[41] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "Conjunto de dj" },
			[42] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "Rack de servidores" },
			[43] = { ["object"] = "prop_gold_trolly_full", ["price"] = 1000, ["label"] = "Trolly con barras de oro" }
		},
	},
	["general4"] = {
		label = "Random 2",
		items = {
			[1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["label"] = "Tonto" },
			[2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["label"] = "Reloj de huevo" },
			[3] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["label"] = "Bolsa de comida" },
			[4] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["label"] = "Palo de escoba 1" },
			[5] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["label"] = "Palo de escoba 2" },
			[6] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["label"] = "Canasta de frutas" },
			[7] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["label"] = "Fruta para la cesta" },
			[8] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["label"] = "Cesta de madera" },
			[9] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["label"] = "Joyeria 1" },
			[10] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["label"] = "Joyeria 2" },
			[11] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["label"] = "Joyeria 3" },
			[12] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["label"] = "Joyeria 4" },
			[13] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["label"] = "Joyeria 5" },
			[14] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["label"] = "Joyeria 6" },
			[15] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["label"] = "Joyeria 7" },
			[16] = { ["object"] = "p_watch_01", ["price"] = 100, ["label"] = "Reloj 1" },
			[17] = { ["object"] = "p_watch_02", ["price"] = 100, ["label"] = "Reloj 2" },
			[18] = { ["object"] = "p_watch_03", ["price"] = 100, ["label"] = "Reloj 3" },
			[19] = { ["object"] = "p_watch_04", ["price"] = 100, ["label"] = "Reloj 4" },
			[20] = { ["object"] = "p_watch_05", ["price"] = 100, ["label"] = "Reloj 5" },
			[21] = { ["object"] = "p_watch_06", ["price"] = 100, ["label"] = "Reloj 6" },
			[22] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["label"] = "Joyeria 8" },
			[23] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["label"] = "Joyeria 9" },
			[24] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["label"] = "Joyeria 10" },
			[25] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["label"] = "Joyeria 11" },
			[26] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["label"] = "Joyeria 12" },
			[27] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["label"] = "Joyeria 13" },
			[28] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["label"] = "Joyeria 14" },
			[29] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["label"] = "Joyeria 15" },
			[30] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["label"] = "Pantalla verde" },
			[31] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["label"] = "Bidón gasolina" },
			[32] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["label"] = "Teclado 1" },
			[33] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["label"] = "Teclado 2" },
			[34] = { ["object"] = "v_corp_bk_secpanel", ["price"] = 1000, ["label"] = "Teclado 3" },
			[35] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["label"] = "maleta 1" },
			[36] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["label"] = "maleta 2" },
			[37] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["label"] = "maleta 3"},
			[38] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["label"] = "oso de peluche" },
			[39] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["label"] = "Bolsas de compra 1" },
			[40] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["label"] = "Bolsas de compra 1" },
			[41] = { ["object"] = "p_ld_sax", ["price"] = 100, ["label"] = "Saxófono" },
			[42] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["label"] = "Balón de fútbol" }
		},
	},
	["small"] = {
		label = "Detalles",
		items = {
			[1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["label"] = "Gato de la estatua" },
			[2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["label"] = "Payaso de la estatua" },
			[3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["label"] = "Estatua autentica" },
			[4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["label"] = "Mujer estatua" },
			[5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["label"] = "Flamenco de la estatua" },
			[6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["label"] = "Mujer estatua" },
			[7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["label"] = "Estatua femenina payaso" },
			[8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["label"] = "Obelisco de la estatua" },
			[9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["label"] = "Pilar de la estatua" },
			[10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["label"] = "La olla" },
			[11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["label"] = "Estatua 1" },
			[12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["label"] = "Estatua 2" },
			[13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["label"] = "Estatua 3" },
			[14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["label"] = "Estatua 4" },
			[15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["label"] = "Skateboard" },
			[16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["label"] = "Bloc de dibujo" },
			[17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["label"] = "Pañuelos" },
			[18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["label"] = "cesta con desorden" },
			[19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["label"] = "Papelera" },
			[20] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["label"] = "Cesta con sobres" },
			[21] = { ["object"] = "prop_idol_01", ["price"] = 100, ["label"] = "Oro de la estatua" },
			[22] = { ["object"] = "v_res_r_fighorsestnd", ["price"] = 300, ["label"] = "Estatua de caballo negro" },
			[23] = { ["object"] = "v_res_r_fighorse", ["price"] = 300, ["label"] = "Estatua gran caballo" },
			[24] = { ["object"] = "v_res_r_figdancer", ["price"] = 300, ["label"] = "Bailarina de la estatua" },
			[25] = { ["object"] = "v_res_fa_idol02", ["price"] = 300, ["label"] = "Estatua del elefante" },
			[26] = { ["object"] = "v_res_m_statue", ["price"] = 300, ["label"] = "Estatua" },
			[27] = { ["object"] = "v_20_ornaeagle", ["price"] = 300, ["label"] = "Estatua águila" },
			[28] = { ["object"] = "v_med_p_vaseround", ["price"] = 300, ["label"] = "Ronda de jarrón" },
			[29] = { ["object"] = "ex_mp_h_acc_vase_05", ["price"] = 300, ["label"] = "Jarrón púrpura" },
			[30] = { ["object"] = "apa_mp_h_acc_dec_head_01", ["price"] = 300, ["label"] = "Pieza de arte" },
			[31] = { ["object"] = "apa_mp_h_acc_dec_sculpt_02", ["price"] = 300, ["label"] = "Pieza de arte 2" },
			[32] = { ["object"] = "ex_mp_h_acc_dec_plate_02", ["price"] = 300, ["label"] = "Pieza de arte 3" },
			[33] = { ["object"] = "apa_mp_h_acc_bowl_ceramic_01", ["price"] = 300, ["label"] = "Bol" }
		},
	},
	["storage"] = {
		label = "Almacenamiento",
		items = {
			[1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["label"] = "Gabinete grande" },
			[2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["label"] = "Tocador" },
			[3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["label"] = "Unidad lateral" },
			[4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["label"] = "Unidad lateral" },
			[5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["label"] = "Unidad lateral" },
			[6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["label"] = "Unidad de cama" },
			[7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["label"] = "Unidad de TV" },
			[8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["label"] = "Unidad de cómoda" },
			[9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["label"] = "Unidad de fondo" },
			[10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["label"] = "Unidad de consola" },
			[11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["label"] = "Unidad de armario" },
			[12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["label"] = "Unidad de cofre" },
			[13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["label"] = "Unidad de Mason" },
			[14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["label"] = "Gabinete" },
			[15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["label"] = "Unidad lateral" },
			[16] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["label"] = "Unidad lateral" },
			[17] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["label"] = "Unidad lateral 2" },
			[18] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["label"] = "Unidad de libro" },
			[19] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["label"] = "Unidad de caja" },
			[20] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["label"] = "Unidad de almacenamiento" },
			[21] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["label"] = "Unidad de vestuario" },
			[22] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["label"] = "Unidad de madera" },
			[23] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["label"] = "Bolsa de frijoles 1" },
			[24] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["label"] = "Mil cajón 1" },
			[25] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["label"] = "Mil cajón 2" },
			[26] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["label"] = "Caja fuerte" },
			[27] = { ["object"] = "prop_toolchest_05", ["price"] = 5000, ["label"] = "Banco de elaboración" },
			[28] = { ["object"] = "v_corp_filecablow", ["price"] = 500, ["label"] = "Gabinete de archivo bajo" },
			[29] = { ["object"] = "v_corp_filecabtall", ["price"] = 500, ["label"] = "Gabinete de archivo alto" },
			[30] = { ["object"] = "apa_mp_h_str_shelffloorm_02", ["price"] = 500, ["label"] = "Gabinete moderno grande" },
			[31] = { ["object"] = "prop_coathook_01", ["price"] = 100, ["label"] = "Coatear" },
			[32] = { ["object"] = "v_corp_lowcabdark01", ["price"] = 500, ["label"] = "Gabinete de archivo negro negro" },
			[33] = { ["object"] = "v_corp_tallcabdark01", ["price"] = 500, ["label"] = "Archivo gabinete alto negro" },
			[34] = { ["object"] = "v_corp_cabshelves01", ["price"] = 1000, ["label"] = "Archivo gabinete negrok" },
			[35] = { ["object"] = "v_corp_offshelf", ["price"] = 1000, ["label"] = "Archivo Gabinete grande" },
			[36] = { ["object"] = "apa_mp_h_str_sideboardl_06", ["price"] = 750, ["label"] = "Gabinete moderno" },
			[37] = { ["object"] = "apa_mp_h_str_sideboardl_09", ["price"] = 750, ["label"] = "Gabinete moderno 2" },
			[38] = { ["object"] = "apa_mp_h_str_shelfwallm_01", ["price"] = 750, ["label"] = "Gabinete de libros 2" },
			[39] = { ["object"] = "apa_mp_h_str_sideboardl_11", ["price"] = 750, ["label"] = "Gabinete moderno 3" },
			[40] = { ["object"] = "prop_box_wood02a_pu", ["price"] = 100, ["label"] = "Cajón militar" },
			[41] = { ["object"] = "prop_mb_cargo_02a", ["price"] = 100, ["label"] = "Cajón de suministro" },
			[42] = { ["object"] = "imp_prop_impexp_rack_01a", ["price"] = 100, ["label"] = "Bastidor con cosas 1" },
			[43] = { ["object"] = "imp_prop_impexp_rack_02a", ["price"] = 100, ["label"] = "Bastidor con cosas 2" },
			[44] = { ["object"] = "imp_prop_impexp_rack_03a", ["price"] = 100, ["label"] = "Bastidor con cosas 3" },
			[45] = { ["object"] = "imp_prop_impexp_rack_04a", ["price"] = 100, ["label"] = "Bastidor con cosas 4" },
			[46] = { ["object"] = "prop_rub_cage01b", ["price"] = 100, ["label"] = "Trolly con cajas" },
			[47] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["label"] = "Vestidor" },
			[48] = { ["object"] = "v_club_rack", ["price"] = 500, ["label"] = "Perchero" },
			[49] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["label"] = "Aparador" },
			[50] = { ["object"] = "v_16_high_bed_mesh_unit", ["price"] = 300, ["label"] = "Gabinete con cosas" },
			[51] = { ["object"] = "mp_b_str_avunitl_01", ["price"] = 300, ["label"] = "Gabinete marrón grande" },
			[52] = { ["object"] = "ch_chint03_hacker", ["price"] = 300, ["label"] = "Escritorio con monitores 1" },
			[53] = { ["object"] = "xm_prop_base_staff_desk_01", ["price"] = 300, ["label"] = "Escritorio con monitores 2" },
			[54] = { ["object"] = "v_corp_deskseta", ["price"] = 300, ["label"] = "Escritorio con monitores 2" },
			[55] = { ["object"] = "bkr_prop_gunlocker_01a", ["price"] = 100, ["label"] = "Estantería de armas" }
		},
	},
	["electronics"] = {
		label = "Electrónica",
		items = {
			[1] = { ["object"] = "ba_prop_battle_club_computer_01", ["price"] = 300, ["label"] = "Ordenador con teclado" },
			[2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["label"] = "Altavoz" },
			[3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["label"] = "Muelle de altavoz " },
			[4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["label"] = "Trastero" },
			[5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["label"] = "Teléfono" },
			[6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["label"] = "Fanático de la torre" },
			[7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["label"] = "Ventilador" },
			[8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["label"] = "Pantalla grande" },
			[9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["label"] = "Monitor" },
			[10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["label"] = "Mixer" },
			[11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["label"] = "CCTV" },
			[12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["label"] = "Laptop" },
			[13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["label"] = "Monitor" },
			[14] = { ["object"] = "prop_speaker_05", ["price"] = 500, ["label"] = "Altavoz montado" },
			[15] = { ["object"] = "prop_tv_flat_03b", ["price"] = 1000, ["label"] = "Pequeña pantalla plana " },
			[16] = { ["object"] = "prop_laptop_01a", ["price"] = 750, ["label"] = "Portátil abierto" },
			[17] = { ["object"] = "prop_tv_flat_michael", ["price"] = 3000, ["label"] = "Pared de pantalla plana" },
			[18] = { ["object"] = "prop_dyn_pc", ["price"] = 1000, ["label"] = "PC" },
			[19] = { ["object"] = "prop_keyboard_01b", ["price"] = 100, ["label"] = "Teclado" },
			[20] = { ["object"] = "prop_mouse_01b", ["price"] = 100, ["label"] = "Ratón de computadora" },
			[21] = { ["object"] = "v_ret_gc_phone", ["price"] = 100, ["label"] = "Telefono de oficina" },
			[22] = { ["object"] = "prop_tv_flat_01", ["price"] = 5000, ["label"] = "Pantalla plana grande" },
			[23] = { ["object"] = "prop_arcade_01", ["price"] = 5000, ["label"] = "Arcade" },
			[24] = { ["object"] = "prop_console_01", ["price"] = 250, ["label"] = "Consola de juego" },
			[25] = { ["object"] = "v_res_tre_dvdplayer", ["price"] = 250, ["label"] = "Reproductor de DVD" },
			[26] = { ["object"] = "prop_speaker_08", ["price"] = 500, ["label"] = "Altavoz de madera" },
			[27] = { ["object"] = "prop_cctv_mon_02", ["price"] = 300, ["label"] = "Monitor de CCTV" },
			[28] = { ["object"] = "prop_tv_flat_02", ["price"] = 2500, ["label"] = "Pantalla plana" },
			[29] = { ["object"] = "prop_cctv_cam_01a", ["price"] = 300, ["label"] = "Cctv 2" },
			[30] = { ["object"] = "prop_dest_cctv_02", ["price"] = 300, ["label"] = "Monitor de CCTV 2" },
			[31] = { ["object"] = "prop_cctv_cam_07a", ["price"] = 300, ["label"] = "Cctv 3" },
			[32] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "Conjunto de dj" },
			[33] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "rack de servidores" },
			[34] = { ["object"] = "prop_elecbox_18", ["price"] = 100, ["label"] = "Gabinete de electricidad" }
		},
	},
	["lighting"] = {
		label = "Iluminación",
		items = {
			[1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["label"] = "Lámpara de escritorio corp" },
			[2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["label"] = "Lámpara de escritorio" },
			[3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["label"] = "Lámpara aa" },
			[4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["label"] = "Lámpara 1" },
			[5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["label"] = "Lámpara de piso" },
			[6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["label"] = "Lámpara 2" },
			[7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["label"] = "Lámpara de mesa" },
			[8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["label"] = "Lámpara de mesa 2" },
			[9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["label"] = "Lámpara de cama" },
			[10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["label"] = "Lámpara de Lengua Planta" },
			[11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["label"] = "Lámpara de mesa3" },
			[12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["label"] = "Soporte de lámpara" },
			[13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["label"] = "Soporte de lámpara 2" },
			[14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["label"] = "Lámpara de mesa4" },
			[15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["label"] = "Ventilador ligero" },
			[16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["label"] = "Lámpara alta" },
			[17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["label"] = "Luz de pared" },
			[18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["label"] = "Abrazadera" },
			[19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["label"] = "Luz parpadeante" },
			[20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["label"] = "Luz de pared lateral" },
			[21] = { ["object"] = "prop_wall_light_07a", ["price"] = 100, ["label"] = "Linterna" },
			[22] = { ["object"] = "prop_wall_light_01a", ["price"] = 100, ["label"] = "Lámpara de pared" },
			[23] = { ["object"] = "v_serv_tu_light2_", ["price"] = 100, ["label"] = "Luz industrial" },
			[24] = { ["object"] = "v_serv_tu_light3_", ["price"] = 100, ["label"] = "Luz industrial 2" },
			[25] = { ["object"] = "ba_prop_battle_lights_ceiling_l_a", ["price"] = 300, ["label"] = "Lámpara de techo" },
			[26] = { ["object"] = "v_med_p_floorlamp", ["price"] = 300, ["label"] = "Lámpara grande" },
			[27] = { ["object"] = "v_club_vu_lamp", ["price"] = 100, ["label"] = "Lámpara pequeña" },
			[28] = { ["object"] = "ba_prop_battle_lights_wall_l_a", ["price"] = 100, ["label"] = "lámpara de pared" },
			[29] = { ["object"] = "ba_prop_battle_lights_ceiling_l_c", ["price"] = 300, ["label"] = "Lámpara de techo 2" },
			[30] = { ["object"] = "ba_prop_battle_lights_ceiling_l_b", ["price"] = 300, ["label"] = "Candelabro 2" },
			[31] = { ["object"] = "ba_prop_battle_lights_wall_l_c", ["price"] = 100, ["label"] = "lámpara de pared 2" },
			[32] = { ["object"] = "ba_prop_battle_lights_wall_l_b", ["price"] = 100, ["label"] = "lámpara de pared 3" },
			[33] = { ["object"] = "hei_heist_lit_lightpendant_02", ["price"] = 300, ["label"] = "Lámpara de techo 3" },
			[34] = { ["object"] = "prop_oldlight_01b", ["price"] = 100, ["label"] = "lámpara de pared4" },
			[35] = { ["object"] = "v_ind_cflight02", ["price"] = 100, ["label"] = "Lámpara de techo " },
			[36] = { ["object"] = "v_ind_cflight", ["price"] = 100, ["label"] = "Lámpara de techo 2" },
			[37] = { ["object"] = "xm_prop_base_wall_lampa", ["price"] = 100, ["label"] = "Lámpara industrial grande 1" },
			[38] = { ["object"] = "xm_prop_base_wall_lampb", ["price"] = 100, ["label"] = "Lámpara industrial grande 1" },
			[39] = { ["object"] = "apa_mp_h_lit_floorlampnight_07", ["price"] = 100, ["label"] = "Lámpara azul " }
		},
	},
	["tables"] = {
		label = "Mesas",
		items = {
			[1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["label"] = "Mesa de centro 1" },
			[2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["label"] = "Mesa redonda" },
			[3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["label"] = "Mesa auxiliar pequeña" },
			[4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["label"] = "Mesa A" },
			[5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["label"] = "Mesa B" },
			[6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["label"] = "Mesa C" },
			[7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["label"] = "Comedor" },
			[8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["label"] = "Mesa de centro 2" },
			[9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["label"] = "Mesa baja" },
			[10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["label"] = "Mesa de cama" },
			[11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["label"] = "Escritorio" },
			[12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["label"] = "Mesa auxiliar" },
			[13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["label"] = "Mesa de consola" },
			[14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["label"] = "Comedor 2" },
			[15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["label"] = "Consola de mesa" },
			[16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["label"] = "Heces" },
			[17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["label"] = "Mesa de aparador" },
			[18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["label"] = "Mesa 2" },
			[19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["label"] = "Mesa de televisión" },
			[20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["label"] = "Mesa de televisión 2" },
			[21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["label"] = "Mesa de café" },
			[22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["label"] = "Escritorio." },
			[23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["label"] = "Mesa de yate 1" },
			[24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["label"] = "Mesa de yate 2" },
			[25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["label"] = "Mesa de yate 3" },
			[26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["label"] = "Tabla de CSR" },
			[27] = { ["object"] = "v_res_mconsoletrad", ["price"] = 250, ["label"] = "mesa alta" },
			[28] = { ["object"] = "v_ilev_liconftable_sml", ["price"] = 500, ["label"] = "mesa de reuniones" },
			[29] = { ["object"] = "v_ret_tablesml", ["price"] = 350, ["label"] = "mesa marillaux" },
			[30] = { ["object"] = "apa_mp_h_yacht_coffee_table_02", ["price"] = 500, ["label"] = "Mesa de centro marrón" },
			[31] = { ["object"] = "apa_mp_h_yacht_side_table_01", ["price"] = 300, ["label"] = "marrón de mesa" },
			[32] = { ["object"] = "apa_mp_h_yacht_side_table_02", ["price"] = 300, ["label"] = "mesa redonda" },
			[33] = { ["object"] = "apa_mp_h_tab_sidelrg_04", ["price"] = 300, ["label"] = "mesa redonda 2" },
			[34] = { ["object"] = "v_club_vu_table", ["price"] = 300, ["label"] = "Mesa hecha" },
			[35] = { ["object"] = "apa_mp_h_tab_sidelrg_07", ["price"] = 500, ["label"] = "Mesa de centro de vidrio" },
			[36] = { ["object"] = "bkr_prop_weed_table_01b", ["price"] = 100, ["label"] = "mesa plegable" },
			[37] = { ["object"] = "ba_prop_int_trad_table", ["price"] = 300, ["label"] = "mesa alta" },
			[38] = { ["object"] = "apa_mp_h_str_sideboards_02", ["price"] = 750, ["label"] = "vidrio" },
			[39] = { ["object"] = "apa_mp_h_yacht_coffee_table_01", ["price"] = 750, ["label"] = "mesa de centro moderna" },
			[40] = { ["object"] = "apa_mp_h_din_table_04", ["price"] = 1000, ["label"] = "vidrio de mesa de comedor" },
			[41] = { ["object"] = "bkr_prop_coke_table01a", ["price"] = 1000, ["label"] = "Mesa de methproduction" },
			[42] = { ["object"] = "gr_prop_gr_bench_03b", ["price"] = 1500, ["label"] = "Mesa de pared con armas." },
			[43] = { ["object"] = "gr_prop_gr_bench_04b", ["price"] = 1500, ["label"] = "Mesa de pared con armas. 2" },
			[44] = { ["object"] = "gr_prop_gr_bench_01b", ["price"] = 1500, ["label"] = "Mesa de pared con armas. 3" },
		},
	},
	["plants"] = {
		label = "Plantas",
		items = {
			[1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["label"] = "Planta FIB" },
			[2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["label"] = "Planta bomba" },		
			[3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["label"] = "Flores" },	
			[4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["label"] = "Planta china" },	
			[5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["label"] = "Planta platano" },	
			[6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["label"] = "Palmera" },	
			[7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["label"] = "Palmera 2" },	
			[8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["label"] = "Urna de plantas" },	
			[9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["label"] = "Goma de plantas" },	
			[10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["label"] = "Planta" },	
			[11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["label"] = "Árbol de plantas" },	
			[12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["label"] = "Plantas" },	
			[13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["label"] = "Flores" },
			[14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["label"] = "Flores 1" },
			[15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["label"] = "Flores 2" },	
			[16] = { ["object"] = "v_res_m_vasefresh", ["price"] = 300, ["label"] = "Flores de jarrón" },
			[17] = { ["object"] = "v_res_rosevasedead", ["price"] = 300, ["label"] = "Florero de rosas 2" },
			[18] = { ["object"] = "v_res_exoticvase", ["price"] = 300, ["label"] = "Florero 3" },
			[19] = { ["object"] = "v_res_rosevase", ["price"] = 300, ["label"] = "Florero de Rose" },
			[20] = { ["object"] = "prop_pot_plant_6a", ["price"] = 300, ["label"] = "Colgante" },
			[21] = { ["object"] = "prop_pot_plant_02a", ["price"] = 300, ["label"] = "Maceta" },
			[22] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["label"] = "Flores 4" },
		},
	},
	["kitchen"] = {
		label = "Cocina",
		items = {
			[1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["label"] = "Lavadora 1" },
			[2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["label"] = "Lavadora 2" },
			[3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["label"] = "Lavadora 3" },
			[4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["label"] = "Cesto de la ropa" },
			[5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["label"] = "Nevera 1" },
			[6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["label"] = "Nevera 2" },
			[7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["label"] = "Nevera 3" },
			[8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["label"] = "Nevera 4" },
			[9] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["label"] = "Nevera 5" },
			[10] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["label"] = "Nevera 6" },
			[11] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["label"] = "Cocina 1" },
			[12] = { ["object"] = "v_res_ovenhobmod", ["price"] = 1000, ["label"] = "Cocina 2" },
			[13] = { ["object"] = "prop_micro_01", ["price"] = 150, ["label"] = "Microonda 1" },
			[14] = { ["object"] = "prop_micro_02", ["price"] = 150, ["label"] = "Microonda 2" },
			[15] = { ["object"] = "prop_wok", ["price"] = 150, ["label"] = "Wok" },
			[16] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["label"] = "Plato de pastel" },
			[17] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["label"] = "Tabla de cortar" },
			[18] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["label"] = "Utensilios" },
			[19] = { ["object"] = "v_res_pestle", ["price"] = 150, ["label"] = "Majadero" },
			[20] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["label"] = "Papelas 1" },
			[21] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["label"] = "Papelas 2" },
			[22] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["label"] = "lata 1" },
			[23] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["label"] = "lata 2" },
			[24] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["label"] = "lata 3" },
			[25] = { ["object"] = "prop_pot_03", ["price"] = 150, ["label"] = "lata 4" },
			[26] = { ["object"] = "prop_pot_04", ["price"] = 150, ["label"] = "lata 5" },
			[27] = { ["object"] = "prop_pot_05", ["price"] = 150, ["label"] = "lata 6" },
			[28] = { ["object"] = "prop_pot_06", ["price"] = 150, ["label"] = "lata 7" },
			[29] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["label"] = "lata 8" },
			[30] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["label"] = "Juicer" },
			[31] = { ["object"] = "v_res_mkniferack", ["price"] = 100, ["label"] = "Cuchillos" },
			[32] = { ["object"] = "v_res_mchopboard", ["price"] = 100, ["label"] = "Tabla de cortar" },
			[33] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["label"] = "Pava" }
		},
	},
	["bathroom"] = {
		label = "Baño",
		items = {
			[1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["label"] = "Inodoro 1" },
			[2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["label"] = "Inodoro 2" },
			[3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["label"] = "Inodoro 3" },
			[4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["label"] = "Lavabo 1" },
			[5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["label"] = "Lavabo 2" },
			[6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["label"] = "Lavabo 3" },
			[7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["label"] = "Lavabo 4" },
			[8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["label"] = "Dispensador de jabón" },
			[9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["label"] = "Estante de ducha" },
			[10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["label"] = "Secador de manos 1" },
			[11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["label"] = "Secador de manos 2" },
			[12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["label"] = "Riel de toalla 1" },
			[13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["label"] = "Riel de toalla 2" },
			[14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["label"] = "Toalla 1" },
			[15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["label"] = "Toalla 2" },
			[16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["label"] = "Toalla 3" },
			[17] = { ["object"] = "v_ilev_mm_faucet", ["price"] = 100, ["label"] = "Grifo" },
			[18] = { ["object"] = "v_res_tre_washbasket", ["price"] = 250, ["label"] = "Cesto de la ropa" },
			[19] = { ["object"] = "prop_toilet_soap_02", ["price"] = 100, ["label"] = "Jabón" },
			[20] = { ["object"] = "prop_bar_sink_01", ["price"] = 100, ["label"] = "Lavabo 1" },
			[21] = { ["object"] = "v_res_mbath", ["price"] = 100, ["label"] = "Baño 1" },
			[22] = { ["object"] = "apa_mp_h_bathtub_01", ["price"] = 1000, ["label"] = "Baño 2" }
		}
	},
	["medical"] = {
		label = "Médico",
		items = {
			[1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["label"] = "Barril" },
			[2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["label"] = "Cárcel de mono" },
			[3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["label"] = "Caja de mono grande" },
			[4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["label"] = "Cama 1" },
			[5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["label"] = "Cama 2" },
			[6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["label"] = "Cama de mesa." },
			[7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["label"] = "Escritorio  1" },
			[8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["label"] = "Escritorio  2" },
			[9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["label"] = "Escritorio  Centro" },
			[10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["label"] = "Escritorio  Set" },
			[11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["label"] = "Mesa grande" },
			[12] = { ["object"] = "v_med_bin", ["price"] = 150, ["label"] = "Papelera" },
			[13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["label"] = "Centrífugo" },
			[14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["label"] = "Enfriador" },
			[15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["label"] = "Monitor" },
			[16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["label"] = "Mesa de autopsia" },
			[17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["label"] = "Papelera" },
			[18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["label"] = "Trolley" },
			[19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["label"] = "Quimicos" },
			[20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["label"] = "Mesa de BLM." },
			[21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["label"] = "Caja de archivo" },
			[22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["label"] = "Cabina de archivo" },
			[23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["label"] = "Manguera" },
			[24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["label"] = "Armario grande" },
			[25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["label"] = "Caja ligera" },
			[26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["label"] = "Medstool." },
			[27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["label"] = "Mini nevera" },
			[28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["label"] = "Toallas de papel." },
			[29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["label"] = "Fotocopia" },
			[30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["label"] = "soporte TV" },
			[31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["label"] = "Unidad de pared" },
			[32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["label"] = "Luz de examen" },
			[33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["label"] = "Tanque de gas" },
			[34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["label"] = "Scan Hazmat" },
			[35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["label"] = "Pared de cabeza" },
			[36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["label"] = "Asientos" },
			[37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["label"] = "Mesa de hospital" },
			[38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["label"] = "Guantera" },
			[39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["label"] = "Cubo de la basura" },
			[40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["label"] = "Oscilador" },
			[41] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["label"] = "Unidad HD 1" },
			[42] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["label"] = "Unidad HD 2" },
			[43] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["label"] = "Primeros auxilios" },
			[44] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["label"] = "Sierra para huesos" },
			[45] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["label"] = "Medkit" }
		},
	},
	["walldecoration"] = {
		label = "Decoración Pared",
		items = {
			[1] = { ["object"] = "apa_p_h_acc_artwalll_02", ["price"] = 1000, ["label"] = "Cuadro" },
			[2] = { ["object"] = "v_ind_cs_toolboard", ["price"] = 500, ["label"] = "Herramientas" },
			[3] = { ["object"] = "ex_office_swag_paintings03", ["price"] = 1000, ["label"] = "Suelo de pinturas" },
			[4] = { ["object"] = "ex_mp_h_acc_artwallm_03", ["price"] = 750, ["label"] = "Cuadro abstracto" },
			[5] = { ["object"] = "ex_p_h_acc_artwallm_04", ["price"] = 750, ["label"] = "Cuadro abstracto 2" },
			[6] = { ["object"] = "ex_p_h_acc_artwalll_01", ["price"] = 1250, ["label"] = "Cuadro abstracto Large" },
			[7] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 750, ["label"] = "Cuadro abstracto 3" },
			[8] = { ["object"] = "ex_mp_h_acc_artwallm_02", ["price"] = 750, ["label"] = "Cuadro abstracto 4" },
			[9] = { ["object"] = "ex_p_h_acc_artwallm_03", ["price"] = 750, ["label"] = "Cuadro abstracto 5" },
			[10] = { ["object"] = "apa_mp_h_acc_artwallm_02", ["price"] = 750, ["label"] = "Cuadro abstracto 6" },
			[11] = { ["object"] = "apa_mp_h_acc_artwalll_02", ["price"] = 750, ["label"] = "Cuadro abstracto 7" },
			[12] = { ["object"] = "apa_mp_h_acc_artwallm_04", ["price"] = 750, ["label"] = "Cuadro abstracto 8" },
			[13] = { ["object"] = "prop_dart_bd_cab_01", ["price"] = 250, ["label"] = "Tablero de dardos" },
			[14] = { ["object"] = "prop_dart_bd_01", ["price"] = 250, ["label"] = "Tablero de dardos 2" }
		},
	},
}